version: '3.6'
services:
  grafana:
    hostname: grafana  
    container_name: grafana
    image: grafana/grafana:8.1.2
    ports:
      - 3000:3000
    user: "$UID:$GID"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USER=spark
      - GF_SECURITY_ADMIN_PASSWORD=TldhTl1!
    volumes:
      - /data/docker/grafana-data:/var/lib/grafana
    restart: always

