version: '3.6'
services:
  influxdb2:
    hostname: influxdb2
    container_name: influxdb2
    image: influxdb:2.0.8-alpine    
    ports:
      - 8086:8086
    volumes:
      - /docker/influxdb2-data:/var/lib/influxdb2
      - /docker/influxdb2-config:/etc/influxdb2
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=coc
      - DOCKER_INFLUXDB_INIT_PASSWORD="TldhTl1!"
      - DOCKER_INFLUXDB_INIT_ORG=CCS
      - DOCKER_INFLUXDB_INIT_BUCKET=k8s-metrics