version: '3.6'
services:
  influxdb2:
    hostname: influxdb2
    container_name: influxdb2
    image: influxdb:2.0.8-alpine    
    ports:
      - 8086:8086
    volumes:
      - /data/docker/influxdb2-data:/var/lib/influxdb2
      - /data/docker/influxdb2-config:/etc/influxdb2
    restart: always
    environment:
      - INFLUXD_HTTP_BIND_ADDRESS=:8086
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=spark
      - DOCKER_INFLUXDB_INIT_PASSWORD=TldhTl1!
      - DOCKER_INFLUXDB_INIT_ORG=COC
      - DOCKER_INFLUXDB_INIT_BUCKET=k8s-metrics
      - DOCKER_INFLUXDB_INIT_RETENTION=365d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=T9NROHMS7027kgtLa3Bq3v3oNNrB9gscIi85Zvin2cd0vIaIo-eO8J-Q0TNjg_jEEe-NgI_RPWgXcoQdEc-QTA==