version: '3.6'
services:
  telegraf:
    image: telegraf:1.19.3
    container_name: telegraf
#    ports:
#      - 8092:8092
#      - 8094:8094
#      - 8125:8125
    volumes:
      - ./data/inftelegra/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: always
    networks:
      netgroup:
        ipv4_address: 172.18.0.93
networks:
  netgroup:
    name: netgroup
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1