---
kind: ConfigMap
apiVersion: v1
metadata: 
  name: kube-dns
  namespace: kube-system
data:
  upstreamNameservers: |
    ["8.8.8.8"]
---
kind: Service
apiVersion: v1
metadata: 
  name: kafka1
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 19091
      targetPort: 19091
---
apiVersion: v1
kind: Endpoints
metadata: 
  name: kafka1
  namespace: kube-system
subsets: 
- addresses:
  - ip: 172.18.0.81
  ports: 
  - port: 19091

---
kind: Service
apiVersion: v1
metadata: 
  name: kafka2
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 19092
      targetPort: 19092
---
apiVersion: v1
kind: Endpoints
metadata: 
  name: kafka2
  namespace: kube-system
subsets: 
- addresses:
  - ip: 172.18.0.82
  ports: 
  - port: 19092

---
kind: Service
apiVersion: v1
metadata: 
  name: kafka3
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 19093
      targetPort: 19093
---
apiVersion: v1
kind: Endpoints
metadata: 
  name: kafka3
  namespace: kube-system
subsets: 
- addresses:
  - ip: 172.18.0.83
  ports: 
  - port: 19093
---