---
kind: ConfigMap
apiVersion: v1
metadata: 
  name: kube-dns
  namespace: kube-system
data:
  upstreamNameservers: |
    ["8.8.8.8"]
---
kind: Service
apiVersion: v1
metadata: 
  name: kafka1
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Endpoints
metadata: 
  name: kafka1
  namespace: kube-system
subsets: 
- addresses:
  - ip: 192.168.54.139
  ports: 
  - port: 9092
---
kind: Service
apiVersion: v1
metadata: 
  name: kafka2
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093  
---
apiVersion: v1
kind: Endpoints
metadata: 
  name: kafka2
  namespace: kube-system
subsets: 
- addresses:
  - ip: 192.168.54.139
  ports: 
  - port: 9093
---
kind: Service
apiVersion: v1
metadata: 
  name: kafka3
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
---
apiVersion: v1
kind: Endpoints
metadata: 
  name: kafka3
  namespace: kube-system
subsets: 
- addresses:
  - ip: 192.168.54.139
  ports: 
  - port: 9094
---